### PR TITLE
implement configurable view file extension

### PR DESCRIPTION
**Pull request by SimonHarte**
#54

### CODE REVIEW

**Comment by SimonHarte** [comment]
Tests are not failing when executed locally, with node version 0.12.9 and npm version 2.14.9, I don't know what the problem is there...

**Comment by SimonHarte** [comment]
Tests don't fail locally with the same node and npm version and same procedure...

**Comment by deniaz** [comment]
Rerunning the tests on travis fixed the issues.

**Comment by SimonHarte** [comment]
Closing this, should be made onto develop instead of master.

**Pull request closed without merging**
