### PR TITLE
ci: upgrade npm

### PR DESCRIPTION
**Pull request by DanielRuf**
## Purpose of this pull request? 

* Other, please explain:
Upgrade npm to the latest version.

The pull request refers to the:

* generator (generator-nitro)

## What changes did you make?

Update the Travis CI config.

### CODE REVIEW

**Comment by ernscht** [comment]
Thanks for your contribution.
I see. Currently, npm version 6.4.1 will be the better choice than 5.6.0.
But i'd rather like to use the matching npm version to each node version.
Would this be possible with travis?

**Comment by ernscht** [comment]
I'm closing this in favor of https://github.com/namics/generator-nitro/pull/141

Thanks for your hint and your input.

> Not the best solution as you can independently update npm which is also done in general (faster, more stable, more secure, ...).

But if we look at past, it's probably the safer solution to use the matching version.

> Devs are advised to regularly upgrade / update npm

Never heard of this advice.
Using the appropriate npm version has proven to be very useful. Especially using a package-lock.json

**Comment by DanielRuf** [comment]
> Using the appropriate npm version has proven to be very useful. Especially using a package-lock.json

Pre npm@5 lockfiles are not used. But generally the lockfiles do not work when people install generator-nitro, they just work on the root level. npmjs ignores them.

**Comment by DanielRuf** [comment]
No, if you install eg generator-nitro with `npm i namics/generator-nitro`, it does not use its internal lockfile.

Also you have now different results on XI. The cprrect reproducible build for libs does not use lockfiles normally - if we want to mirror how consumers use the lib / generator.

**Comment by DanielRuf** [comment]
`npm ci` is meant for root lockfiles for projects / apps.

**Pull request closed without merging**
