### PR TITLE
WIP: ci: test on Windows using Travis CI

### PR DESCRIPTION
**Pull request by DanielRuf**
## Purpose of this pull request? 

We can also test on Windows using Travis CI.

* Other, please explain:

CI improvement, one less CI provider (AppVeyor is slow).

The pull request refers to the:

* generator (generator-nitro)

## What changes did you make?
Update Travis CI config.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Probably related to the npm version. Normally it works (we test on all 3 platforms for zurb/foundation-sites using Travis CI).

I'll check if a new triggered build might solve this or if it is an issue with npm on Windows Server 2016 and the Travis CI image.

Just keep this PR open (I'll rebase if needed).

**Comment by ernscht** [comment]
Closing for now, due to lack of activity.

**Comment by DanielRuf** [comment]
Please reopen, I probaly just forgot this one.

**Comment by ernscht** [comment]
Closed again - still unsuccessful windows build on travis

**Pull request closed without merging**
