### PR TITLE
[WIP] provide yeoman generator for views

### PR DESCRIPTION
**Pull request by SimonHarte**
#30

### CODE REVIEW

**Comment by ernscht** [comment]
some notes:
* compatibility 
    * backwards compatibility (missing views node in `config.json`)
    * does it work with your other PR #59 ?
* concept
    * doesn't work if `config.nitro.view_directory` is configured
    * do we need `views.path` in `config.json`?
    * is `name` the right wording for the first argument, you use it more like an URL?
    * it's not yet possible to create a view in a subfolder
* consistency
    * do we need `name`, `title` and `file` for view replacements?
    * `views` & `view`
    * A PR should be based on the newest sources
* documentation

**Comment by SimonHarte** [comment]
Thanks for the feedback!
In response to your points:
- compatibility
 - what do you suggest here? This is a new feature, so new configuration parameters might be introduced, is that a problem?
 - It is compatible with my other PR, merged them locally without any issues.
- concept
 - I have to look into the case when `view_directory` is configured
 - I structured the new `view` config node similar to the `components` node, we could of course hard code this part because it doesn't need to change like with components.
 - I think `name` is fine, I don't really see how I'm using it as a URL, I'm just creating the files here. Not an issue for me changing this to whatever you think might be better :)
 - Didn't think of this option, can you give me a use case? I'm not quite familiar with how Nitro builds routes. Of course we could also extend the generator with sort of a "type", which might also open up the possibility to create partials if you meant that, but I assumed this could be implemented with its own generator (`yo nitro:partial` or similar).
- consistency
 - `file` doesn't seem to be needed, good point.
 - This is also similar to `components` and `component`.
 - Updated to latest develop, I forgot to update my forks' develop before branching...
- documentation
 - Good point! I knew I forgot something when creating the PR!

**Comment by SimonHarte** [comment]
I've fixed some points, I'm not quite happy with the fact that I need to install the node module `extend` as dev dependency in the generator and copy it into the test directory for `config.js` to work.
The other way it seems would be to first run the nitro generator and then nitro:view before tests so all needed files are created, but I didn't get that to work...

Creating subfolders inside views would be the next point.

**Comment by SimonHarte** [comment]
Could you rerun the Travis build please? Tests run through locally without any issues (node 0.12.9).

**Comment by deniaz** [comment]
@SimonHarte done (eventhough I'm not ernscht 😏)

**Comment by ernscht** [comment]
I suggest to close this. There is some work to do.
We should meet to discuss the open issues.

**Comment by SimonHarte** [comment]
I guess we can still keep this WIP and update it later, doesn't hurt anyone. @ernscht

**Comment by ernscht** [comment]
please make a new clean PR

**Pull request closed without merging**
