### PR TITLE
Feature/#183 enhance pattern helper with type parameter

### PR DESCRIPTION
**Pull request by janwidmer**
## Purpose of this pull request? 

* Documentation update
* Enhancement

The pull request refers to the:

* generator (generator-nitro)
* nitro app (@nitro/app)
* example nitro project (project-nitro)
* example nitro project with twig engine (project-nitro-twig)

## What changes did you make?

Enhance the hbs pattern helper to have an optional type parameter. Using this parameter, one can call a pattern within a specific pattern type folder and therefore the pattern name only needs to be unique per pattern type folder

### CODE REVIEW

**Comment by ernscht** [comment]
great enhancement, will have a look soon

**Comment by ernscht** [comment]
Works great. But one thing.
Elements are not covered. Element names has to be unique. How to proceed with this?

**Comment by janwidmer** [comment]
please recheck, added changes according to our discussion

**Review by ernscht — APPROVED** [review]
perfect, thank you

**Pull request merged**
